# Generated by Django 3.2.9 on 2021-12-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_avgscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avgscore',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='avgscore',
            name='neighbourhood',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
